**Question 4**

In [6]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/ladkevinkumar/group9-dsb/Gold 100years.csv
/kaggle/input/datasets/ladkevinkumar/group9-dsb/Brent Oil.csv
/kaggle/input/datasets/ladkevinkumar/group9-dsb/silver 100 years.csv

In [7]:
import pandas as pd

silver_df = pd.read_csv("/kaggle/input/datasets/ladkevinkumar/group9-dsb/silver 100 years.csv")
gold_df = pd.read_csv("/kaggle/input/datasets/ladkevinkumar/group9-dsb/Gold 100years.csv")
oil_df = pd.read_csv("/kaggle/input/datasets/ladkevinkumar/group9-dsb/Brent Oil.csv")

In [8]:
def convert_date(df):
    df["Date"] = pd.to_datetime(df["Date"])
    df["Month"] = df["Date"].dt.month
    df["Year"] = df["Date"].dt.year
    return df

silver_df = convert_date(silver_df)
gold_df = convert_date(gold_df)
oil_df = convert_date(oil_df)

print("Silver Dataset")
display(silver_df.head())

print("Gold Dataset")
display(gold_df.head())

print("Brent Oil Dataset")
display(oil_df.head())

Silver Dataset

        Date  Value  Month  Year
0 1915-01-01   0.51      1  1915
1 1915-02-01   0.51      2  1915
2 1915-03-01   0.51      3  1915
3 1915-04-01   0.51      4  1915
4 1915-05-01   0.51      5  1915

Gold Dataset

        Date  Value  Month  Year
0 1915-01-01  19.25      1  1915
1 1915-02-01  19.25      2  1915
2 1915-03-01  19.25      3  1915
3 1915-04-01  19.25      4  1915
4 1915-05-01  19.25      5  1915

Brent Oil Dataset

        Date  Value  Month  Year
0 1946-01-01  21.23      1  1946
1 1946-02-01  21.35      2  1946
2 1946-03-01  21.11      3  1946
3 1946-04-01  22.79      4  1946
4 1946-05-01  22.67      5  1946

In [10]:
silver_df.to_csv("silver_month_year.csv", index=False)
gold_df.to_csv("gold_month_year.csv", index=False)
oil_df.to_csv("brent_oil_month_year.csv", index=False)